# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="image_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="task",
            name="video_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
