# Generated by Django 6.0.3 on 2026-03-28 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningplan',
            options={'verbose_name': 'خطة تعلم', 'verbose_name_plural': 'خطط التعلم'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'سؤال اختبار', 'verbose_name_plural': 'أسئلة الاختبار'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'مهمة', 'verbose_name_plural': 'المهام'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-join_date'], 'verbose_name': 'ملف مستخدم', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cvs_count',
            field=models.IntegerField(default=0, help_text='عدد السير الذاتية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='progress',
            field=models.IntegerField(default=0, help_text='نسبة التقدم %'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learning_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.learningplan'),
        ),
    ]
