# Generated by Django 6.0.3 on 2026-03-30 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_task_content_task_image_url_task_topic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['topic', 'order', 'created_at'], 'verbose_name': 'مهمة', 'verbose_name_plural': 'المهام'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'موضوع', 'verbose_name_plural': 'المواضيع'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, help_text='ترتيب المهمة داخل الموضوع'),
        ),
        migrations.AddField(
            model_name='task',
            name='resources',
            field=models.JSONField(blank=True, default=list, help_text='مصادر إضافية'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, help_text='محتوى المهمة أو وصفها', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='image_url',
            field=models.URLField(blank=True, help_text='رابط صورة', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='هل المهمة مكتملة؟'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='اسم المهمة', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(default=1, help_text='الموضوع المرتبط بالمهمة', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='video_url',
            field=models.URLField(blank=True, help_text='رابط فيديو تعليمي', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, help_text='وصف الموضوع', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0, help_text='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='skills_count',
            field=models.IntegerField(default=0, help_text='عدد المهارات'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tasks_count',
            field=models.IntegerField(default=0, help_text='عدد المهام'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(help_text='عنوان الموضوع', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cvs_count',
            field=models.IntegerField(default=0, help_text='عدد السير الذاتية'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='progress',
            field=models.IntegerField(default=0, help_text='نسبة التقدم %'),
        ),
    ]
