# Generated by Django 6.0.3 on 2026-03-30 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_task_options_alter_topic_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CVision', help_text='اسم الموقع', max_length=100)),
                ('default_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', help_text='اللغة الافتراضية للموقع', max_length=10)),
                ('session_timeout', models.IntegerField(default=30, help_text='مدة انتهاء الجلسة بالدقائق')),
                ('two_factor_auth', models.BooleanField(default=False, help_text='تفعيل المصادقة الثنائية للمشرفين')),
                ('allow_registration', models.BooleanField(default=True, help_text='السماح بتسجيل مستخدمين جدد')),
                ('email_notifications', models.BooleanField(default=True, help_text='تفعيل إشعارات البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('placement', 'اختبار تحديد المستوى'), ('task_quiz', 'اختبار المهمة')], default='placement', help_text='نوع السؤال (اختبار تحديد مستوى أو اختبار مهمة)', max_length=20)),
                ('question_text', models.TextField(help_text='نص السؤال')),
                ('option_a', models.CharField(help_text='الخيار الأول', max_length=500)),
                ('option_b', models.CharField(help_text='الخيار الثاني', max_length=500)),
                ('option_c', models.CharField(blank=True, help_text='الخيار الثالث (اختياري)', max_length=500, null=True)),
                ('option_d', models.CharField(blank=True, help_text='الخيار الرابع (اختياري)', max_length=500, null=True)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='الحرف المقابل للإجابة الصحيحة (A, B, C, D)', max_length=1)),
                ('order', models.IntegerField(default=0, help_text='ترتيب ظهور السؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, help_text='المهمة المرتبطة بالسؤال (لاختبارات المهام)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='dashboard.task')),
                ('topic', models.ForeignKey(blank=True, help_text='الموضوع المرتبط بالسؤال (لاختبارات تحديد المستوى)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='dashboard.topic')),
            ],
            options={
                'verbose_name': 'سؤال اختبار',
                'verbose_name_plural': 'أسئلة الاختبار',
                'ordering': ['question_type', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(help_text='إجابة المستخدم (A, B, C, D)', max_length=1)),
                ('is_correct', models.BooleanField(default=False, help_text='هل الإجابة صحيحة؟')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نتيجة اختبار',
                'verbose_name_plural': 'نتائج الاختبارات',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
