# Generated by Django 6.0.3 on 2026-03-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_systemsetting_question_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', help_text='مستوى صعوبة الموضوع (سهل، متوسط، صعب)', max_length=10),
        ),
    ]
