# Generated by Django 6.0.3 on 2026-05-24 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_topic_difficulty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_type', 'order', 'created_at'], 'verbose_name': 'السؤال', 'verbose_name_plural': 'الاسئلة'},
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Correct answer (A, B, C, D)', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(help_text='Option A', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(help_text='Option B', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, help_text='Option C (optional)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, help_text='Option D (optional)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, help_text='Question order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Question text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('placement', 'Placement Test'), ('task_quiz', 'Task Quiz')], default='placement', help_text='Question type', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Related task (for task quizzes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='dashboard.task'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Related topic (for placement tests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='dashboard.topic'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
