# Generated by Django 6.0.3 on 2026-06-12 16:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_quizquestion_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='الصورة الشخصية للمستخدم', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_images/'),
        ),
    ]
