# Generated by Django 6.0.3 on 2026-06-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_userprofile_bio_google_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image_url',
            field=models.URLField(blank=True, help_text='رابط صورة', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='video_url',
            field=models.URLField(blank=True, help_text='رابط فيديو تعليمي', max_length=2048, null=True),
        ),
    ]
