# Generated by Django 6.0.3 on 2026-04-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercv',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'CV', 'verbose_name_plural': 'CVs'},
        ),
    ]
