# Generated by Django 6.0.3 on 2026-05-24 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_quizquestion_alter_question_options_and_more'),
        ('userr', '0002_alter_usercv_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='اسم ملف السيرة الذاتية', max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], default='pdf', max_length=10)),
                ('file_path', models.FileField(blank=True, help_text='مسار ملف السيرة الذاتية', null=True, upload_to='cvs/')),
                ('analysis_score', models.IntegerField(default=0, help_text='نسبة التوافق مع الخطة %')),
                ('analysis_data', models.JSONField(blank=True, default=dict, help_text='بيانات التحليل الكاملة')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('learning_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='dashboard.learningplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تحليل سيرة ذاتية',
                'verbose_name_plural': 'تحليلات السير الذاتية',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
