# Generated by Django 6.0.3 on 2026-05-31 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_quizquestion_alter_question_options_and_more'),
        ('userr', '0003_analysishistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_tasks', models.IntegerField(default=0, help_text='عدد المهام المكتملة')),
                ('total_tasks', models.IntegerField(default=0, help_text='إجمالي عدد المهام')),
                ('progress_percentage', models.IntegerField(default=0, help_text='نسبة التقدم %')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='dashboard.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقدم المستخدم في الموضوع',
                'verbose_name_plural': 'تقدم المستخدمين في المواضيع',
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
