# Generated by Django 6.0.3 on 2026-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0005_quizattempt_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='earned_marks',
            field=models.IntegerField(default=0, help_text='مجموع الدرجات التي حصل عليها المستخدم'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_marks',
            field=models.IntegerField(default=0, help_text='مجموع درجات الأسئلة'),
        ),
    ]
