# Generated by Django 6.0.3 on 2026-06-15 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plans', '0001_initial'),
        ('userr', '0006_quizattempt_earned_marks_quizattempt_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='plan_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='learning_plans.task'),
        ),
    ]
